# Generated by Django 3.0.3 on 2020-07-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200724_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='27-07-20'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='27-07-20'),
        ),
    ]
